#!/bin/bash

sudo apt install -y \
acpi \
alsa-base \
alsa-utils \
anacron \
audacious \
autotiling \
avahi-autoipd \
avahi-daemon \
azote \
bc \
bluetuith \
bluez \
bluez-cups \
bluez-obexd \
brightnessctl \
ca-certificates \
calcurse \
cliphist \
cups \
cups-bsd \
cups-client \
cups-filters \
curl \
desktop-file-utils \
dracut \
drm-info \
engrampa \
fastfetch \
firefox \
fontconfig \
fonts-arphic-ukai \
fonts-arphic-uming \
fonts-dejavu-core \
fonts-font-awesome \
fonts-font-awesome-6 \
fonts-hack \
fonts-liberation \
fonts-liberation2 \
fonts-noto-cjk \
fonts-noto-color-emoji \
fonts-noto-core \
fonts-opensymbol \
fonts-ubuntu \
foot \
foomatic-db-compressed-ppds \
fwupd \
fwupd-signed \
gamemode \
ghostscript \
gnome-firmware \
gnome-software \
go-mtpfs \
greetd \
grimshot \
gron \
gstreamer1.0-alsa \
gstreamer1.0-pipewire \
gstreamer1.0-plugins-base \
gstreamer1.0-plugins-base-apps \
gstreamer1.0-plugins-good \
gtklock \
gvfs-backends \
gvfs-fuse \
hplip \
htop \
imv \
inotify-tools \
inxi \
inputattach \
iw \
language-selector-common \
laptop-detect \
libfuse2t64 \
libglib2.0-bin \
libnss-mdns \
libreoffice-calc \
libreoffice-gtk3 \
libreoffice-impress \
libreoffice-style-yaru \
libreoffice-writer \
libsasl2-modules \
lximage-qt \
mako-notifier \
mate-calc \
mate-polkit-bin \
memtest86+ \
mesa-utils \
mobile-broadband-provider-info \
modemmanager \
mpv \
musikcube \
neovim \
network-manager \
nwg-bar \
nwg-clipman \
nwg-displays \
nwg-drawer \
nwg-look \
nwg-wrapper \
openprinting-ppds \
packagekit \
pavucontrol \
pcmanfm \
pcmciautils \
pipewire-audio \
playerctl \
plocate \
pluma \
plymouth-theme-ubuntu-sway-logo \
plymouth-theme-ubuntu-sway-text \
policykit-desktop-privileges \
power-profiles-daemon \
poweralertd \
ppa-purge \
printer-driver-brlaser \
printer-driver-c2esp \
printer-driver-foo2zjs \
printer-driver-gutenprint \
printer-driver-m2300w \
printer-driver-min12xxw \
printer-driver-pnm2ppa \
printer-driver-ptouch \
printer-driver-pxljr \
printer-driver-sag-gdi \
printer-driver-splix \
pulseaudio-utils \
pulsemixer \
python3-requests \
qt6-wayland \
qt6ct \
qtwayland5 \
qutebrowser \
ranger \
rfkill \
simple-scan \
slurp \
snapd \
software-properties-gtk \
spice-vdagent \
swappy \
sway \
sway-input-config \
sway-systemd \
swaybg \
swayidle \
swaykbdd \
swayr \
system-config-printer \
systemd-oomd \
thermald \
transmission-gtk \
tuigreet \
ubuntu-drivers-common \
ubuntu-sway-artwork \
ubuntu-sway-default-settings \
ubuntu-sway-grub-theme \
ubuntu-sway-welcome \
udisks2 \
unzip \
update-notifier \
upower \
usb-creator-gtk \
usb-modeswitch \
vulkan-tools \
waybar \
wayland-utils \
wev \
wf-recorder \
wl-clipboard \
wl-mirror \
wlsunset \
wofi \
wpasupplicant \
wtype \
wvdial \
xdg-desktop-portal-gtk \
xdg-desktop-portal-wlr \
xdg-user-dirs \
xdg-utils \
xkb-data \
xsettingsd \
xwayland \
zathura \
zathura-cb \
zathura-djvu \
zathura-pdf-poppler \
zip